name: example
description: Example app for circular_progress_with_logo package
publish_to: 'none'

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  circular_progress_with_logo:
    path: ../

flutter:
  uses-material-design: true
